"""add rank to positions table

Revision ID: 14d59f578c58
Revises: 9afb224e2fd4
Create Date: 2025-08-23 15:33:24.832892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14d59f578c58'
down_revision: Union[str, Sequence[str], None] = '9afb224e2fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_items')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_name'), ['name'], unique=False)

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_unique_constraint('_parent_name_uc', ['parent_id', 'name'])

    # with op.batch_alter_table('regions', schema=None) as batch_op:
    #     batch_op.drop_constraint('fk_regions_parent_id_regions', type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'regions', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('regions', schema=None) as batch_op:
    #     batch_op.drop_constraint('fk_regions_parent_id_regions', type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'regions', ['parent_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_constraint('_parent_name_uc', type_='unique')
        batch_op.drop_column('rank')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_name'))
        batch_op.drop_index(batch_op.f('ix_items_id'))
        batch_op.alter_column('name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('_alembic_tmp_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
