"""add departments table and link to members

Revision ID: 650419adcbee
Revises: ff41ca9b6c06
Create Date: 2025-08-24 02:04:36.181855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '650419adcbee'
down_revision: Union[str, Sequence[str], None] = 'ff41ca9b6c06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_name'))
        batch_op.create_unique_constraint('uq_departments_name', ['name'])

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_members_department_id_departments', 'departments', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_constraint('fk_members_department_id_departments', type_='foreignkey')
        batch_op.drop_column('department_id')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint('uq_departments_name', type_='unique')
        batch_op.create_index(batch_op.f('ix_departments_name'), ['name'], unique=1)

    # ### end Alembic commands ###
