"""Add parent_id to positions table

Revision ID: 9afb224e2fd4
Revises: 48fdb4246c7e
Create Date: 2025-08-23 10:36:01.221926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9afb224e2fd4'
down_revision: Union[str, Sequence[str], None] = '48fdb4246c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_positions_parent_id', 'positions', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_positions_parent_id', type_='foreignkey')
        batch_op.drop_column('parent_id')
    # ### end Alembic commands ###
