"""Add is_primary to MemberPosition

Revision ID: fd6c64576b2c
Revises: f81d0c6d3714
Create Date: 2025-08-19 00:10:25.033705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd6c64576b2c'
down_revision: Union[str, Sequence[str], None] = 'f81d0c6d3714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_positions', sa.Column('is_primary', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_positions', 'is_primary')
    # ### end Alembic commands ###
