"""add department table and link to member

Revision ID: ff41ca9b6c06
Revises: 14d59f578c58
Create Date: 2025-08-24 01:10:42.811343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff41ca9b6c06'
down_revision: Union[str, Sequence[str], None] = '14d59f578c58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member_positions', schema=None) as batch_op:
        batch_op.alter_column('is_primary',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_regions_parent_id_regions', 'regions', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_regions_parent_id_regions', type_='foreignkey')

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('member_positions', schema=None) as batch_op:
        batch_op.alter_column('is_primary',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###
